package com.springboot.first.start.mybatis;

import java.io.Serializable;

public class UserInfoKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_info_id
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    private Long userInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_info_id
     *
     * @return the value of user_info.user_info_id
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    public Long getUserInfoId() {
        return userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_info_id
     *
     * @param userInfoId the value for user_info.user_info_id
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    public void setUserInfoId(Long userInfoId) {
        this.userInfoId = userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userInfoId=").append(userInfoId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}