package com.springboot.first.start.mybatis;

import java.io.Serializable;
import java.util.Date;

public class UserInfo extends UserInfoKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_phone
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_email
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.datachange_createtime
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    private Date datachangeCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.datachange_lasttime
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    private Date datachangeLasttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_phone
     *
     * @return the value of user_info.user_phone
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_phone
     *
     * @param userPhone the value for user_info.user_phone
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_email
     *
     * @return the value of user_info.user_email
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_email
     *
     * @param userEmail the value for user_info.user_email
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.datachange_createtime
     *
     * @return the value of user_info.datachange_createtime
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    public Date getDatachangeCreatetime() {
        return datachangeCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.datachange_createtime
     *
     * @param datachangeCreatetime the value for user_info.datachange_createtime
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    public void setDatachangeCreatetime(Date datachangeCreatetime) {
        this.datachangeCreatetime = datachangeCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.datachange_lasttime
     *
     * @return the value of user_info.datachange_lasttime
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.datachange_lasttime
     *
     * @param datachangeLasttime the value for user_info.datachange_lasttime
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Fri Dec 07 15:08:01 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userName=").append(userName);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", datachangeCreatetime=").append(datachangeCreatetime);
        sb.append(", datachangeLasttime=").append(datachangeLasttime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}